global:
  scrape_interval: 1m
  scrape_timeout: 5s
rule_files:
  - alert.rules.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
scrape_configs:
  - job_name: myjob
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - "172.18.117.234:8081"
          - "172.18.117.234:8082"
