version: '3'
services:
  alertmanager:
    image: prom/alertmanager
    ports:
    - 9093:9093
    volumes:
    - ./alertmanager:/etc/alertmanager
  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    environment:
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_BASIC_ENABLED=false