// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type UserUpdated struct {
	User *User  `json:"user"`
	Info string `json:"info"`
}
